export const resource = '/order';
export const orderTotalInfoEndpoint = '/order/total';

export const SET_UPDATED_ORDER_IN_STORE_DIRECTLY =
  'SET_UPDATED_ORDER_IN_STORE_DIRECTLY';
export const CHECKOUT__CREATE_ORDER_REQUEST = 'CHECKOUT__CREATE_ORDER_REQUEST';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR';

export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR';

export const GET_ORDER_BY_ID_REQUEST = 'GET_ORDER_BY_ID_REQUEST';
export const GET_ORDER_BY_ID_SUCCESS = 'GET_ORDER_BY_ID_SUCCESS';
export const GET_ORDER_BY_ID_ERROR = 'GET_ORDER_BY_ID_ERROR';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_ERROR = 'UPDATE_ORDER_ERROR';

export const GET_ORDERS_TOTAL_INFO_REQUEST = 'GET_ORDERS_TOTAL_INFO_REQUEST';
export const GET_ORDERS_TOTAL_INFO_SUCCESS = 'GET_ORDERS_TOTAL_INFO_SUCCESS';
export const GET_ORDERS_TOTAL_INFO_ERROR = 'GET_ORDERS_TOTAL_INFO_ERROR';

export const SET_ORDERS_TOTAL = 'SET_ORDERS_TOTAL';
export const COMPLETE_ORDER = 'COMPLETE_ORDER';
