export const DND_DRAG_END = 'DND_DRAG_END';
export const DND_ITEMS_REORDERED = 'DND_ITEMS_REORDERED';
export const INITIALIZE_DROPPABLE = 'INITIALIZE_DROPPABLE';
export const SET_DND_STATE_FOR_DROPPABLE = 'SET_DND_STATE_FOR_DROPPABLE';
export const TOGGLE_DND_MODE_FOR_DROPPABLE = 'TOGGLE_DND_MODE_FOR_DROPPABLE';
export const RESET_DND = 'RESET_DND';

export const MENU_RESTAURATOR__SAVE_MENU_ITEMS_REORDERING =
  'MENU_RESTAURATOR__SAVE_MENU_ITEMS_REORDERING';
