import { ReduxCrudService } from '../../services';

export const resource = '/category';

export const CHANGE_CATEGORIES_ORDERING = 'CHANGE_CATEGORIES_ORDERING';

export const PATCH_CATEGORY_EXTRAS_REQUEST = 'PATCH_CATEGORY_EXTRAS_REQUEST';
export const PATCH_CATEGORY_EXTRAS_SUCCESS = 'PATCH_CATEGORY_EXTRAS_SUCCESS';
export const PATCH_CATEGORY_EXTRAS_ERROR = 'PATCH_CATEGORY_EXTRAS_ERROR';

export const {
  GET: [
    GET_CATEGORY_LIST_REQUEST,
    GET_CATEGORY_LIST_SUCCESS,
    GET_CATEGORY_LIST_ERROR,
  ],
  POST: [
    CREATE_CATEGORY_REQUEST,
    CREATE_CATEGORY_SUCCESS,
    CREATE_CATEGORY_ERROR,
  ],
  GET_BY_ID: [
    GET_CATEGORY_BY_ID_REQUEST,
    GET_CATEGORY_BY_ID_SUCCESS,
    GET_CATEGORY_BY_ID_ERROR,
  ],
  PATCH: [
    UPDATE_CATEGORY_REQUEST,
    UPDATE_CATEGORY_SUCCESS,
    UPDATE_CATEGORY_ERROR,
  ],
  DELETE: [
    DELETE_CATEGORY_REQUEST,
    DELETE_CATEGORY_SUCCESS,
    DELETE_CATEGORY_ERROR,
  ],
} = ReduxCrudService.getActionCrudTypes(resource);

export const SET_CATEGORY_FILTERS = `${resource}/filters/changed`;

export const CLEANUP_CATEGORIES = `${resource}/cleanup`;

export const CLEAR_MANAGED_CATEGORY = 'CLEAR_MANAGED_CATEGORY';
