import { ReduxCrudService } from '../../services';

export const CHECKOUT__BULK_SAVE = 'CHECKOUT__BULK_SAVE';
export const CHECKOUT__PUT_ITEM = 'CHECKOUT__PUT_ITEM';
export const CHECKOUT__CREATE_NEW_ITEM = 'CHECKOUT__CREATE_NEW_ITEM';
export const CHECKOUT__INCREASE_ITEM_AMOUNT = 'CHECKOUT__INCREASE_ITEM_AMOUNT';
export const CHECKOUT__REMOVE_ITEM = 'CHECKOUT__REMOVE_ITEM';
export const CHECKOUT__BULK_CREATE_CHECKOUT_ITEMS =
  'CHECKOUT__BULK_CREATE_CHECKOUT_ITEMS';

export const CHECKOUT__SAVE_TO_STORAGE = 'SAVE_CHECKOUT_TO_LOCAL_STORAGE';
export const CHECKOUT__CLEAR_FROM_STORAGE = 'CHECKOUT__CLEAR_FROM_STORAGE';
export const CHECKOUT__RESTORE_FROM_STORAGE = 'CHECKOUT__RESTORE_FROM_STORAGE';

export const CHECKOUT__SET_UI = 'CHECKOUT__SET_UI';
export const CHECKOUT__BACK_TO_RESTAURANT_MENU =
  'CHECKOUT__BACK_TO_RESTAURANT_MENU';

export const CHECKOUT__UPDATE_ITEM = 'CHECKOUT__UPDATE_ITEM';
export const CHECKOUT__CLEAR = 'CHECKOUT__CLEAR';

export const chargeResource = '/payment/charge';
export const {
  POST: [CREATE_CHARGE_REQUEST, CREATE_CHARGE_SUCCESS, CREATE_CHARGE_ERROR],
} = ReduxCrudService.getActionCrudTypes(chargeResource);
