export const OPEN_DISH_ORDER_MODAL = 'OPEN_DISH_ORDER_MODAL';
export const DISH_ORDER_MODAL__CLOSE = 'DISH_ORDER_MODAL__CLOSE';

export const DISH_ORDER_MODAL__SET_STATE = 'DISH_ORDER_MODAL__SET_STATE';
export const DISH_ORDER_MODAL__TRIGGER_PUT_ITEM_TO_CHECKOUT =
  'DISH_ORDER_MODAL__TRIGGER_PUT_ITEM_TO_CHECKOUT';
export const DISH_ORDER_MODAL__TRIGGER_UPDATING_CHECKOUT_ITEM =
  'DISH_ORDER_MODAL__TRIGGER_UPDATING_CHECKOUT_ITEM';
