export const RESTAURATOR_ORDER_MODAL__SET_STATE =
  'RESTAURATOR_ORDER_MODAL__SET_STATE';
export const RESTAURATOR_ORDER_MODAL__CLOSE = 'RESTAURATOR_ORDER_MODAL__CLOSE';

export const RESTAURATOR_ORDER_MODAL__OPEN_EDITING =
  'RESTAURATOR_ORDER_MODAL__OPEN_EDITING';
export const RESTAURATOR_ORDER_MODAL__OPEN_CREATION =
  'RESTAURATOR_ORDER_MODAL__OPEN_CREATION';

export const RESTAURATOR_ORDER_MODAL__OPEN_ORDER_ITEM_FOR_EDITING =
  'RESTAURATOR_ORDER_MODAL__OPEN_ORDER_ITEM_FOR_EDITING';
export const RESTAURATOR_ORDER_MODAL__OPEN_ORDER_ITEM_CREATION_MODAL =
  'RESTAURATOR_ORDER_MODAL__OPEN_ORDER_ITEM_CREATION_MODAL';

export const RESTAURATOR_ORDER_MODAL__TRIGGER_ADD_ITEM_TO_ORDER =
  'RESTAURATOR_ORDER_MODAL__TRIGGER_ADD_ITEM_TO_ORDER';

export const RESTAURATOR_ORDER_MODAL__UPDATE_ORDER =
  'RESTAURATOR_ORDER_MODAL__UPDATE_ORDER';

export const RESTAURATOR_ORDER_MODAL__CREATE_ORDER =
  'RESTAURATOR_ORDER_MODAL__CREATE_ORDER';
